# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'robot_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *


class MAIN_W(QMainWindow):
    signal_write_msg = QtCore.pyqtSignal(str)
    def __init__(self):
        super(MAIN_W, self).__init__()
        self.setObjectName("变电站巡检机器人系统")
        self.resize(1337, 935)
        self.setWindowFlags(QtCore.Qt.WindowMinimizeButtonHint | QtCore.Qt.WindowCloseButtonHint)  # 禁用最大化
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet("#centralwidget{border-image:url(picture/KindSteel.jpg);}")
        self.topwidget_nm = QtWidgets.QWidget(self.centralwidget)
        self.topwidget_nm.setGeometry(QtCore.QRect(30, 20, 1031, 41))
        self.topwidget_nm.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.topwidget_nm.setObjectName("topwidget_nm")
        self.layoutWidget = QtWidgets.QWidget(self.topwidget_nm)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 161, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 B")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Bold")
        font.setPointSize(9)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("#comboBox{\n"
                                        "border: 2px solid gray;\n"
                                        "border-radius:4px;\n"
                                        "padding:1px 2px 1px 2px;\n"
                                        "min-width :  6em;\n"
                                        "}\n"
                                        "#comboBox:down-arrow{\n"
                                        "    image: url(picture/icondown.jpg);\n"
                                        "}\n"
                                        "#comboBox:drop-down{\n"
                                        "    width: 25px;\n"
                                        "}")
        self.horizontalLayout.addWidget(self.comboBox)
        self.layoutWidget_2 = QtWidgets.QWidget(self.topwidget_nm)
        self.layoutWidget_2.setGeometry(QtCore.QRect(230, 10, 151, 31))   #350, 10, 151, 31
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 B")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Bold")
        font.setPointSize(9)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("#comboBox_2{\n"
                                        "border: 2px solid gray;\n"
                                        "border-radius:4px;\n"
                                        "padding:1px 2px 1px 2px;\n"
                                        "min-width :  5em;\n"
                                        "}\n"
                                        "#comboBox_2:down-arrow{\n"
                                        "    image: url(picture/icondown.jpg);\n"
                                        "}\n"
                                        "#comboBox_2:drop-down{\n"
                                        "    width: 25px;\n"
                                        "}")
        self.horizontalLayout_2.addWidget(self.comboBox_2)
        self.layoutWidget_4 = QtWidgets.QWidget(self.topwidget_nm)
        self.layoutWidget_4.setGeometry(QtCore.QRect(730, 10, 251, 31))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_ip = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 B")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_ip.setFont(font)
        self.label_ip.setObjectName("label_ip")
        self.horizontalLayout_4.addWidget(self.label_ip)
        self.IPEdit = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.IPEdit.setObjectName("IPadress")
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Bold")
        font.setPointSize(9)
        self.IPEdit.setFont(font)
        self.IPEdit.setStyleSheet("#IPadress{\n"
                                    "border: 2px solid gray;\n"
                                    "border-radius:9px;\n"
                                    "}")
        self.horizontalLayout_4.addWidget(self.IPEdit)

        self.layoutWidget_3 = QtWidgets.QWidget(self.topwidget_nm)
        self.layoutWidget_3.setGeometry(QtCore.QRect(490, 10, 200, 31))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 B")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.portdit = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.portdit.setObjectName("Portress")
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Bold")
        font.setPointSize(9)
        self.portdit.setFont(font)
        self.portdit.setStyleSheet("#Portress{\n"
                                  "border: 2px solid gray;\n"
                                  "border-radius:9px;\n"
                                  "}")
        self.portdit.setReadOnly(True)
        # self.portdit.setPlaceholderText("8266")
        self.horizontalLayout_3.addWidget(self.portdit)

        self.rob_image = QtWidgets.QLabel(self.centralwidget)
        self.rob_image.setGeometry(QtCore.QRect(420, 10, 70, 60))
        self.rob_image.setStyleSheet("image: url(picture/robot_head.jpg);")
        self.rob_image.setText("")
        self.rob_image.setObjectName("rob_image")


        self.grap_nm = QtWidgets.QWidget(self.centralwidget)
        self.grap_nm.setGeometry(QtCore.QRect(650, 80, 391, 801))
        self.grap_nm.setObjectName("grap_nm")
        self.label_4 = QtWidgets.QLabel(self.grap_nm)
        self.label_4.setGeometry(QtCore.QRect(105, 16, 181, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.picture_output1 = QtWidgets.QLabel(self.grap_nm)
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(13)
        self.picture_output1.setFont(font)
        self.picture_output1.setGeometry(QtCore.QRect(20, 50, 341, 251))
        self.picture_output1.setObjectName("picture_output1")
        self.picture_output1.setAlignment(Qt.AlignCenter)
        self.la_video1 = QtWidgets.QLabel(self.grap_nm)
        self.la_video1.setGeometry(QtCore.QRect(-50, -80, 491, 491))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        self.la_video1.setFont(font)
        self.la_video1.setStyleSheet("border-image: url(picture/videoicon.jpg);")
        self.la_video1.setText("")
        self.la_video1.setObjectName("la_video1")
        self.la_video1.lower()
        self.label_6 = QtWidgets.QLabel(self.grap_nm)
        self.label_6.setGeometry(QtCore.QRect(70, 330, 241, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.picture_output2 = QtWidgets.QLabel(self.grap_nm)
        self.picture_output2.setGeometry(QtCore.QRect(20, 360, 351, 281))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(13)
        self.picture_output2.setFont(font)
        self.picture_output2.setObjectName("picture_output2")
        self.picture_output2.setAlignment(Qt.AlignCenter)
        self.la_video2 = QtWidgets.QLabel(self.grap_nm)
        self.la_video2.setGeometry(QtCore.QRect(-50, 230, 491, 501))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        self.la_video2.setFont(font)
        self.la_video2.setStyleSheet("border-image: url(picture/videoicon.jpg);")
        self.la_video2.setText("")
        self.la_video2.setObjectName("la_video2")
        self.la_video2.lower()
        self.label_8 = QtWidgets.QLabel(self.grap_nm)
        self.label_8.setGeometry(QtCore.QRect(30, 680, 81, 21))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.grap_nm)
        self.label_9.setGeometry(QtCore.QRect(220, 680, 111, 21))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.type = QtWidgets.QLineEdit(self.grap_nm)
        self.type.setGeometry(QtCore.QRect(20, 720, 101, 51))
        self.type.setObjectName("type")
        self.type.setAlignment(Qt.AlignCenter)
        self.type.setPlaceholderText("1")
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Bold")
        font.setPointSize(11)
        self.type.setFont(font)
        self.type.setStyleSheet("#type{\n"
                                  "border: 2px solid gray;\n"
                                  "border-radius:9px;\n"
                                  "}")
        self.dushu_line = QtWidgets.QLineEdit(self.grap_nm)
        self.dushu_line.setGeometry(QtCore.QRect(170, 720, 191, 51))
        self.dushu_line.setObjectName("dushu_line")
        self.dushu_line.setAlignment(Qt.AlignCenter)
        self.dushu_line.setReadOnly(True)
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Bold")
        font.setPointSize(11)
        self.dushu_line.setFont(font)
        self.dushu_line.setStyleSheet("#dushu_line{\n"
                                "border: 2px solid gray;\n"
                                "border-radius:9px;\n"
                                "}")

        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1111, 26))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        #状态栏


        self.Page1()
        self.Page2()
        self.Page3()
        self.dock = QDockWidget(self)
        self.dock.setGeometry(0,80,151,741)
        self.stack = QStackedWidget()
        self.stack.addWidget(self.page1)
        self.stack.addWidget(self.page2)
        self.stack.addWidget(self.page3)
        layout = QHBoxLayout()
        layout.addWidget(self.listWidget)
        layout.addWidget(self.stack)
        self.main_widget.setLayout(layout)
        self.listWidget.currentRowChanged.connect(self.display)
        self.dock.setWidget(self.listWidget)
        # self.main_widget.setCentralWidget(self.stack)
        self.addDockWidget(Qt.LeftDockWidgetArea, self.dock)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

        #放置校徽
        self.xiaohui = QtWidgets.QLabel(self.listWidget)
        self.xiaohui.setGeometry(0,0,255,255)
        self.xiaohui.setPixmap(QPixmap(r"C:\Users\86159\PycharmProjects\pyQt-GUI\picture\WUST.jpg"))

        #绘图---画线部分
        self.line_1 = QtWidgets.QFrame(self.centralwidget)
        self.line_1.setGeometry(QtCore.QRect(0, 60, 1100, 20))
        self.line_1.setLineWidth(3)
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName("line_1")

        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(630, 68, 10, 840))
        self.line_2.setLineWidth(3)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")

        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 900, 1100, 20))
        self.line_3.setLineWidth(3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
    def display(self, index):
        if(index == 2):
            self.stack.setCurrentIndex(0)
            self.change_label.setStyleSheet("#change_label{border-image: url(picture/changeicon1.jpg);}\n")
        elif(index == 4):
            self.stack.setCurrentIndex(1)
            self.change_label.setStyleSheet("#change_label{border-image: url(picture/changeicon2.jpg);}\n")
        elif(index == 6):
            self.stack.setCurrentIndex(2)
            self.change_label.setStyleSheet("#change_label{border-image: url(picture/changeicon3.jpg);}\n")
        self.statusbar.showMessage(self.listWidget.item(index).text() + "模块被点击了")
    def Page1(self):
        self.main_widget = QtWidgets.QWidget(self.centralwidget)
        self.main_widget.setGeometry(QtCore.QRect(0, 80, 721, 741))
        self.main_widget.setObjectName("main_widget")
        self.listWidget = QtWidgets.QListWidget(self.main_widget)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 151, 741))
        self.listWidget.setObjectName("listWidget")
        self.listWidget.setStyleSheet("#listWidget{border-image:url(picture/RareWind.jpg);}\n"
                                      "QListView {\n"
                                      "    outline:none;\n"
                                      "    border:none;\n"
                                      "}\n"
                                      " \n"
                                      "#listWidget::item {\n"
                                      "    background-color: rgb(199, 228, 231);\n"
                                      "    color: #000000;\n"
                                      "    border: transparent;\n"
                                      "    border-bottom: 3px solid #dbdbdb;\n"
                                      "    padding: 2px;\n"
                                      "}\n"
                                      " \n"
                                      "#listWidget::item:hover {\n"
                                      "    background-color:  rgb(248, 247, 223);\n"
                                      "}\n"
                                      " \n"
                                      "#listWidget::item:selected {\n"
                                      "    border-left: 12px solid  rgb(248, 247, 223);\n"
                                      "}\n"
                                      "")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(100)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(42)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignBottom)
        font = QtGui.QFont()
        font.setFamily("仓耳今楷05-6763 W05")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        item.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("picture/ai.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(False)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("仓耳今楷05-6763 W05")
        font.setPointSize(12)
        item.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("picture/chilun.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("仓耳今楷05-6763 W05")
        font.setPointSize(12)
        item.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("picture/database.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.listWidget.addItem(item)
        self.change_label = QtWidgets.QLabel(self.listWidget)
        self.change_label.setObjectName("change_label")
        self.change_label.setGeometry(QtCore.QRect(65, 620, 121, 171))
        self.change_label.setText("")
        self.page1 = QtWidgets.QWidget(self.main_widget)
        self.page1.setGeometry(QtCore.QRect(150, 0, 571, 741))
        self.page1.setObjectName("page1")
        self.getipbutton = QtWidgets.QPushButton(self.page1)
        self.getipbutton.setGeometry(QtCore.QRect(20, 20, 161, 31))
        self.getipbutton.setObjectName("getipbutton")
        self.getipbutton.setStyleSheet("#getipbutton{\n"
                                        "    background-color: rgb(255, 255, 255);\n"
                                        "    color: rgb(0, 0, 0);\n"
                                        "    border:3px solid rgb(182, 182, 182);\n"
                                        "    border-radius:8px;\n"
                                        "}\n"
                                        "#getipbutton:hover{\n"
                                        "    background-color: rgb(249, 248, 222);\n"
                                        "    color: rgb(0, 0, 0);\n"
                                        "}\n"
                                        "#getipbutton:pressed{\n"
                                        "    padding-top:5px;\n"
                                        "    padding-left:5px;\n"
                                        "}")
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 R")
        font.setPointSize(11)
        self.getipbutton.setFont(font)
        self.clearrev = QtWidgets.QPushButton(self.page1)
        self.clearrev.setGeometry(QtCore.QRect(408, 510, 93, 28))
        self.clearrev.setObjectName("clearbutton")
        self.clearrev.setStyleSheet("#clearbutton{\n"
                                       "    background-color: rgb(255, 255, 255);\n"
                                       "    color: rgb(0, 0, 0);\n"
                                       "    border:3px solid rgb(12, 120, 228);\n"
                                       "    border-radius:8px;\n"
                                       "}\n"
                                       "#clearbutton:hover{\n"
                                       "    background-color: rgb(240, 234, 237);\n"
                                       "    color: rgb(0, 0, 0);\n"
                                       "}\n"
                                       "#clearbutton:pressed{\n"
                                       "    padding-top:5px;\n"
                                       "    padding-left:5px;\n"
                                       "}")
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 R")
        font.setPointSize(10)
        self.clearrev.setFont(font)

        self.pushButton_9 = QtWidgets.QPushButton(self.page1)
        self.pushButton_9.setGeometry(QtCore.QRect(30, 120, 111, 41))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_9.setStyleSheet("#pushButton_9{\n"
                                        "    background-color: rgb(255, 255, 255);\n"
                                        "    color: rgb(0, 0, 0);\n"
                                        "    border:3px solid rgb(182, 182, 182);\n"
                                        "    border-radius:8px;\n"
                                        "}\n"
                                        "#pushButton_9:hover{\n"
                                        "    background-color: rgb(249, 248, 222);\n"
                                        "    color: rgb(0, 0, 0);\n"
                                        "}\n"
                                        "#pushButton_9:disabled{\n"
                                        "    background-color: rgb(249, 248, 222);\n"
                                        "    color: rgb(0, 0, 0);\n"
                                        "}\n"
                                        "#pushButton_9:pressed{\n"
                                        "    padding-top:5px;\n"
                                        "    padding-left:5px;\n"
                                        "}")
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 R")
        font.setPointSize(10)
        self.pushButton_9.setFont(font)
        self.pushButton_10 = QtWidgets.QPushButton(self.page1)
        self.pushButton_10.setGeometry(QtCore.QRect(190, 120, 111, 41))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_10.setStyleSheet("#pushButton_10{\n"
                                        "    background-color: rgb(255, 255, 255);\n"
                                        "    color: rgb(0, 0, 0);\n"
                                        "    border:3px solid rgb(182, 182, 182);\n"
                                        "    border-radius:8px;\n"
                                        "}\n"
                                        "#pushButton_10:hover{\n"
                                        "    background-color: rgb(249, 248, 222);\n"
                                        "    color: rgb(0, 0, 0);\n"
                                        "}\n"
                                        "#pushButton_10:disabled{\n"
                                        "    background-color: rgb(249, 248, 222);\n"
                                        "    color: rgb(0, 0, 0);\n"
                                        "}\n"
                                        "#pushButton_10:pressed{\n"
                                        "    padding-top:5px;\n"
                                        "    padding-left:5px;\n"
                                        "}")
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 R")
        font.setPointSize(10)
        self.pushButton_10.setFont(font)
        self.Buton_cameraopen = QtWidgets.QPushButton(self.page1)
        self.Buton_cameraopen.setGeometry(QtCore.QRect(30, 220, 111, 41))
        self.Buton_cameraopen.setObjectName("Buton_cameraopen")
        self.Buton_cameraopen.setStyleSheet("#Buton_cameraopen{\n"
                                         "    background-color: rgb(255, 255, 255);\n"
                                         "    color: rgb(0, 0, 0);\n"
                                         "    border:3px solid rgb(182, 182, 182);\n"
                                         "    border-radius:8px;\n"
                                         "}\n"
                                         "#Buton_cameraopen:hover{\n"
                                         "    background-color: rgb(249, 248, 222);\n"
                                         "    color: rgb(0, 0, 0);\n"
                                         "}\n"
                                         "#Buton_cameraopen:pressed{\n"
                                         "    padding-top:5px;\n"
                                         "    padding-left:5px;\n"
                                         "}")
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 R")
        font.setPointSize(10)
        self.Buton_cameraopen.setFont(font)
        self.Buton_cameraclose = QtWidgets.QPushButton(self.page1)
        self.Buton_cameraclose.setGeometry(QtCore.QRect(190, 220, 111, 41))
        self.Buton_cameraclose.setObjectName("Buton_cameraclose")
        self.Buton_cameraclose.setStyleSheet("#Buton_cameraclose{\n"
                                            "    background-color: rgb(255, 255, 255);\n"
                                            "    color: rgb(0, 0, 0);\n"
                                            "    border:3px solid rgb(182, 182, 182);\n"
                                            "    border-radius:8px;\n"
                                            "}\n"
                                            "#Buton_cameraclose:hover{\n"
                                            "    background-color: rgb(249, 248, 222);\n"
                                            "    color: rgb(0, 0, 0);\n"
                                            "}\n"
                                            "#Buton_cameraclose:pressed{\n"
                                            "    padding-top:5px;\n"
                                            "    padding-left:5px;\n"
                                            "}")
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 R")
        font.setPointSize(10)
        self.Buton_cameraclose.setFont(font)
        self.pushButton_13 = QtWidgets.QPushButton(self.page1)
        self.pushButton_13.setGeometry(QtCore.QRect(30, 310, 111, 41))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_13.setStyleSheet("#pushButton_13{\n"
                                             "    background-color: rgb(255, 255, 255);\n"
                                             "    color: rgb(0, 0, 0);\n"
                                             "    border:3px solid rgb(182, 182, 182);\n"
                                             "    border-radius:8px;\n"
                                             "}\n"
                                             "#pushButton_13:hover{\n"
                                             "    background-color: rgb(249, 248, 222);\n"
                                             "    color: rgb(0, 0, 0);\n"
                                             "}\n"
                                             "#pushButton_13:pressed{\n"
                                             "    padding-top:5px;\n"
                                             "    padding-left:5px;\n"
                                             "}")
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 R")
        font.setPointSize(10)
        self.pushButton_13.setFont(font)
        self.pushButton_14 = QtWidgets.QPushButton(self.page1)
        self.pushButton_14.setGeometry(QtCore.QRect(190, 310, 111, 41))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_14.setStyleSheet("#pushButton_14{\n"
                                         "    background-color: rgb(255, 255, 255);\n"
                                         "    color: rgb(0, 0, 0);\n"
                                         "    border:3px solid rgb(182, 182, 182);\n"
                                         "    border-radius:8px;\n"
                                         "}\n"
                                         "#pushButton_14:hover{\n"
                                         "    background-color: rgb(249, 248, 222);\n"
                                         "    color: rgb(0, 0, 0);\n"
                                         "}\n"
                                         "#pushButton_14:pressed{\n"
                                         "    padding-top:5px;\n"
                                         "    padding-left:5px;\n"
                                         "}")
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 R")
        font.setPointSize(10)
        self.pushButton_14.setFont(font)
        self.save_picture = QtWidgets.QPushButton(self.page1)
        self.save_picture.setGeometry(QtCore.QRect(30, 410, 111, 41))
        self.save_picture.setObjectName("save_picture")
        self.save_picture.setStyleSheet("#save_picture{\n"
                                         "    background-color: rgb(255, 255, 255);\n"
                                         "    color: rgb(0, 0, 0);\n"
                                         "    border:3px solid rgb(182, 182, 182);\n"
                                         "    border-radius:8px;\n"
                                         "}\n"
                                         "#save_picture:hover{\n"
                                         "    background-color: rgb(249, 248, 222);\n"
                                         "    color: rgb(0, 0, 0);\n"
                                         "}\n"
                                         "#save_picture:pressed{\n"
                                         "    padding-top:5px;\n"
                                         "    padding-left:5px;\n"
                                         "}")
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 R")
        font.setPointSize(10)
        self.save_picture.setFont(font)
        self.pushButton_16 = QtWidgets.QPushButton(self.page1)
        self.pushButton_16.setGeometry(QtCore.QRect(190, 410, 111, 41))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_16.setStyleSheet("#pushButton_16{\n"
                                        "    background-color: rgb(255, 255, 255);\n"
                                        "    color: rgb(0, 0, 0);\n"
                                        "    border:3px solid rgb(182, 182, 182);\n"
                                        "    border-radius:8px;\n"
                                        "}\n"
                                        "#pushButton_16:hover{\n"
                                        "    background-color: rgb(249, 248, 222);\n"
                                        "    color: rgb(0, 0, 0);\n"
                                        "}\n"
                                        "#pushButton_16:pressed{\n"
                                        "    padding-top:5px;\n"
                                        "    padding-left:5px;\n"
                                        "}")
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 R")
        font.setPointSize(10)
        self.pushButton_16.setFont(font)
        self.label_35 = QtWidgets.QLabel(self.page1)
        self.label_35.setGeometry(QtCore.QRect(340, 30, 201, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.label_35.setStyleSheet('border-width: 3px;border-style: solid;'
'border-color: rgb(12, 120, 228);'
'background-color: rgb(248, 247, 224);')
        self.textBrowser_recv = QtWidgets.QTextBrowser(self.page1)
        self.textBrowser_recv.setGeometry(QtCore.QRect(320, 70, 251, 441))
        self.textBrowser_recv.setObjectName("robet_recvive_data")
        self.textBrowser_recv.setPlaceholderText("请连接网络")
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(11)
        self.textBrowser_recv.setFont(font)

        self.la_picture = QtWidgets.QLabel(self.page1)
        self.la_picture.setGeometry(QtCore.QRect(296, -30, 297, 601))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        self.la_picture.setFont(font)
        self.la_picture.setStyleSheet("border-image: url(picture/biankuang.jpg);")
        self.la_picture.setText("")
        self.la_picture.setObjectName("la_picture")
        self.la_picture.lower()

        self.layoutWidget_2 = QtWidgets.QWidget(self.page1)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 560, 511, 151))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_36 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(12)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.gridLayout_3.addWidget(self.label_36, 0, 0, 1, 1)
        self.cpsend_data_2 = QtWidgets.QTextEdit(self.layoutWidget_2)
        self.cpsend_data_2.setObjectName("cpsend_data_2")
        self.cpsend_data_2.setPlaceholderText("请输入数据")
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(10)
        self.cpsend_data_2.setFont(font)
        self.cpsend_picture = QtWidgets.QLabel(self.page1)
        self.cpsend_picture.setGeometry(QtCore.QRect(-10, 560, 561, 171))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        self.cpsend_picture.setFont(font)
        self.cpsend_picture.setStyleSheet("border-image: url(picture/sendkuang.jpg);")
        self.cpsend_picture.setText("")
        self.cpsend_picture.setObjectName("cpsend_picture")
        self.cpsend_picture.lower()

        self.gridLayout_3.addWidget(self.cpsend_data_2, 1, 0, 1, 1)
        self.sendbutton = QtWidgets.QPushButton(self.layoutWidget_2)
        self.sendbutton.setObjectName("sendbutton")
        self.sendbutton.setStyleSheet("border-image: url(picture/sendicon.jpg);\n"
                                      "    color: rgb(255, 255, 255);")
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(10)
        self.sendbutton.setFont(font)
        self.gridLayout_3.addWidget(self.sendbutton, 2, 0, 1, 1)


    def Page2(self):
        self.page2 = QtWidgets.QWidget(self.centralwidget)
        self.page2.setGeometry(QtCore.QRect(150, 80, 571, 741))
        self.page2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.page2.setObjectName("page2")
        self.label_37 = QtWidgets.QLabel(self.page2)
        self.label_37.setGeometry(QtCore.QRect(20, 30, 121, 21))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 R")
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.page2)
        self.lineEdit_5.setGeometry(QtCore.QRect(500, 20, 51, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.icon_setpart1 = QtWidgets.QLabel(self.page2)
        self.icon_setpart1.setGeometry(QtCore.QRect(553, 20, 35, 31))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        self.icon_setpart1.setFont(font)
        self.icon_setpart1.setStyleSheet("border-image: url(picture/angleicon.jpg);")
        self.icon_setpart1.setText("")
        self.icon_setpart1.setObjectName("icon_setpart1")
        self.horizontalSlider_4 = QtWidgets.QSlider(self.page2)
        self.horizontalSlider_4.setGeometry(QtCore.QRect(150, 20, 331, 31))
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.horizontalSlider_4.setMinimum(0)
        self.horizontalSlider_4.setMaximum(60)
        self.horizontalSlider_4.setSingleStep(1)
        self.horizontalSlider_4.setValue(0)
        self.horizontalSlider_4.setTickPosition(QSlider.TicksBelow)
        self.horizontalSlider_4.setTickInterval(10)
        self.horizontalSlider_5 = QtWidgets.QSlider(self.page2)
        self.horizontalSlider_5.setGeometry(QtCore.QRect(150, 90, 331, 31))
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.page2)
        self.lineEdit_6.setGeometry(QtCore.QRect(500, 90, 51, 31))
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.icon_setpart2 = QtWidgets.QLabel(self.page2)
        self.icon_setpart2.setGeometry(QtCore.QRect(553, 90, 35, 31))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        self.icon_setpart2.setFont(font)
        self.icon_setpart2.setStyleSheet("border-image: url(picture/distanceicon.jpg);")
        self.icon_setpart2.setText("")
        self.icon_setpart2.setObjectName("icon_setpart2")
        self.label_38 = QtWidgets.QLabel(self.page2)
        self.label_38.setGeometry(QtCore.QRect(20, 90, 161, 31))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 R")
        font.setPointSize(10)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.horizontalSlider_6 = QtWidgets.QSlider(self.page2)
        self.horizontalSlider_6.setGeometry(QtCore.QRect(150, 160, 331, 31))
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.horizontalSlider_6.setMinimum(100)
        self.horizontalSlider_6.setMaximum(900)
        self.horizontalSlider_6.setSingleStep(1)
        self.horizontalSlider_6.setValue(100)
        self.horizontalSlider_6.setTickPosition(QSlider.TicksBelow)
        self.horizontalSlider_6.setTickInterval(200)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.page2)
        self.lineEdit_7.setGeometry(QtCore.QRect(500, 160, 51, 31))
        self.lineEdit_7.setObjectName("lineEdit_7")

        self.icon_setpart3 = QtWidgets.QLabel(self.page2)
        self.icon_setpart3.setGeometry(QtCore.QRect(553, 160, 35, 31))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        self.icon_setpart3.setFont(font)
        self.icon_setpart3.setStyleSheet("border-image: url(picture/speedicon.jpg);")
        self.icon_setpart3.setText("")
        self.icon_setpart3.setObjectName("icon_setpart3")

        self.label_39 = QtWidgets.QLabel(self.page2)
        self.label_39.setGeometry(QtCore.QRect(20, 160, 121, 31))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 R")
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")

        self.la_setpart = QtWidgets.QLabel(self.page2)
        self.la_setpart.setGeometry(QtCore.QRect(-60, -50, 741, 341))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        self.la_setpart.setFont(font)
        self.la_setpart.setStyleSheet("border-image: url(picture/page2_seticon.jpg);")
        self.la_setpart.setText("")
        self.la_setpart.setObjectName("la_setpart")
        self.la_setpart.lower()

        self.line_9 = QtWidgets.QFrame(self.page2)
        self.line_9.setGeometry(QtCore.QRect(0, 220, 571, 16))
        self.line_9.setLineWidth(2)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.label_40 = QtWidgets.QLabel(self.page2)
        self.label_40.setGeometry(QtCore.QRect(90, 250, 151, 31))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 R")
        font.setPointSize(12)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.page2)
        self.label_41.setGeometry(QtCore.QRect(350, 250, 141, 31))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 R")
        font.setPointSize(12)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.green_right_2 = QtWidgets.QPushButton(self.page2)
        self.green_right_2.setGeometry(QtCore.QRect(210, 390, 61, 61))
        self.green_right_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("picture/camerarighticon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.green_right_2.setIcon(icon)
        self.green_right_2.setIconSize(QtCore.QSize(70, 70))
        self.green_right_2.setFlat(True)
        self.green_right_2.setObjectName("green_right_2")
        self.green_right_2.setStyleSheet("#green_right_2:pressed{\n"
                                   "    padding-top:5px;\n"
                                   "    padding-left:5px;\n"
                                   "}")

        self.green_buttom_2 = QtWidgets.QPushButton(self.page2)
        self.green_buttom_2.setGeometry(QtCore.QRect(120, 470, 61, 61))
        self.green_buttom_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("picture/camerabuttomicon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.green_buttom_2.setIcon(icon1)
        self.green_buttom_2.setIconSize(QtCore.QSize(70, 70))
        self.green_buttom_2.setFlat(True)
        self.green_buttom_2.setObjectName("green_buttom_2")
        self.green_buttom_2.setStyleSheet("#green_buttom_2:pressed{\n"
                                         "    padding-top:5px;\n"
                                         "    padding-left:5px;\n"
                                         "}")
        self.green_left_2 = QtWidgets.QPushButton(self.page2)
        self.green_left_2.setGeometry(QtCore.QRect(30, 390, 61, 61))
        self.green_left_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("picture/cameralefticon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.green_left_2.setIcon(icon2)
        self.green_left_2.setIconSize(QtCore.QSize(70, 70))
        self.green_left_2.setFlat(True)
        self.green_left_2.setObjectName("green_left_2")
        self.green_left_2.setStyleSheet("#green_left_2:pressed{\n"
                                          "    padding-top:5px;\n"
                                          "    padding-left:5px;\n"
                                          "}")
        self.green_top_2 = QtWidgets.QPushButton(self.page2)
        self.green_top_2.setGeometry(QtCore.QRect(120, 300, 61, 61))
        self.green_top_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("picture/cameratopicon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.green_top_2.setIcon(icon3)
        self.green_top_2.setIconSize(QtCore.QSize(70, 70))
        self.green_top_2.setFlat(True)
        self.green_top_2.setObjectName("green_top_2")
        self.green_top_2.setStyleSheet("#green_top_2:pressed{\n"
                                        "    padding-top:5px;\n"
                                        "    padding-left:5px;\n"
                                        "}")
        self.yellow_top_2 = QtWidgets.QPushButton(self.page2)
        self.yellow_top_2.setGeometry(QtCore.QRect(410, 300, 71, 61))
        self.yellow_top_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.yellow_top_2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("picture/robottopicon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.yellow_top_2.setIcon(icon4)
        self.yellow_top_2.setIconSize(QtCore.QSize(70, 70))
        self.yellow_top_2.setFlat(True)
        self.yellow_top_2.setObjectName("yellow_top_2")
        self.yellow_top_2.setStyleSheet("#yellow_top_2:pressed{\n"
                                       "    padding-top:5px;\n"
                                       "    padding-left:5px;\n"
                                       "}")
        self.yellow_left_2 = QtWidgets.QPushButton(self.page2)
        self.yellow_left_2.setGeometry(QtCore.QRect(330, 380, 71, 71))
        self.yellow_left_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.yellow_left_2.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("picture/robotlefticon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.yellow_left_2.setIcon(icon5)
        self.yellow_left_2.setIconSize(QtCore.QSize(80, 80))
        self.yellow_left_2.setFlat(True)
        self.yellow_left_2.setObjectName("yellow_left_2")
        self.yellow_left_2.setStyleSheet("#yellow_left_2:pressed{\n"
                                        "    padding-top:5px;\n"
                                        "    padding-left:5px;\n"
                                        "}")
        self.yellow_buttom_2 = QtWidgets.QPushButton(self.page2)
        self.yellow_buttom_2.setGeometry(QtCore.QRect(410, 470, 71, 71))
        self.yellow_buttom_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.yellow_buttom_2.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("picture/robotbuttomicon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.yellow_buttom_2.setIcon(icon6)
        self.yellow_buttom_2.setIconSize(QtCore.QSize(80, 80))
        self.yellow_buttom_2.setFlat(True)
        self.yellow_buttom_2.setObjectName("yellow_buttom_2")
        self.yellow_buttom_2.setStyleSheet("#yellow_buttom_2:pressed{\n"
                                         "    padding-top:5px;\n"
                                         "    padding-left:5px;\n"
                                         "}")
        self.yellow_right_2 = QtWidgets.QPushButton(self.page2)
        self.yellow_right_2.setGeometry(QtCore.QRect(490, 380, 61, 71))
        self.yellow_right_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.yellow_right_2.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("picture/robotrighticon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.yellow_right_2.setIcon(icon7)
        self.yellow_right_2.setIconSize(QtCore.QSize(80, 80))
        self.yellow_right_2.setFlat(True)
        self.yellow_right_2.setObjectName("yellow_right_2")
        self.yellow_right_2.setStyleSheet("#yellow_right_2:pressed{\n"
                                           "    padding-top:5px;\n"
                                           "    padding-left:5px;\n"
                                           "}")
        self.line_10 = QtWidgets.QFrame(self.page2)
        self.line_10.setGeometry(QtCore.QRect(280, 230, 20, 341))
        self.line_10.setLineWidth(2)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.page2)
        self.line_11.setGeometry(QtCore.QRect(0, 560, 291, 16))
        self.line_11.setLineWidth(3)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.page2)
        self.line_12.setGeometry(QtCore.QRect(290, 560, 281, 16))
        self.line_12.setLineWidth(3)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.label_42 = QtWidgets.QLabel(self.page2)
        self.label_42.setGeometry(QtCore.QRect(200, 590, 171, 21))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 R")
        font.setPointSize(11)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.plus_2 = QtWidgets.QPushButton(self.page2)
        self.plus_2.setGeometry(QtCore.QRect(140, 640, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.plus_2.setFont(font)
        self.plus_2.setObjectName("plus_2")
        self.plus_2.setStyleSheet("#plus_2{\n"
                                       "    background-color: rgb(255, 255, 255);\n"
                                       "    color: rgb(0, 0, 0);\n"
                                       "    border:3px solid rgb(182, 182, 182);\n"
                                       "    border-radius:8px;\n"
                                       "}\n"
                                       "#plus_2:hover{\n"
                                       "    background-color: rgb(240, 235, 236);\n"
                                       "    color: rgb(0, 0, 0);\n"
                                       "}\n"
                                       "#plus_2:pressed{\n"
                                       "    padding-top:5px;\n"
                                       "    padding-left:5px;\n"
                                       "}")
        self.minus_2 = QtWidgets.QPushButton(self.page2)
        self.minus_2.setGeometry(QtCore.QRect(330, 640, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.minus_2.setFont(font)
        self.minus_2.setObjectName("minus_2")
        self.minus_2.setStyleSheet("#minus_2{\n"
                                  "    background-color: rgb(255, 255, 255);\n"
                                  "    color: rgb(0, 0, 0);\n"
                                  "    border:3px solid rgb(182, 182, 182);\n"
                                  "    border-radius:8px;\n"
                                  "}\n"
                                  "#minus_2:hover{\n"
                                  "    background-color: rgb(240, 235, 236);\n"
                                  "    color: rgb(0, 0, 0);\n"
                                  "}\n"
                                  "#minus_2:pressed{\n"
                                  "    padding-top:5px;\n"
                                  "    padding-left:5px;\n"
                                  "}")
        self.la_cameraicon = QtWidgets.QLabel(self.page2)
        self.la_cameraicon.setGeometry(QtCore.QRect(110, 380, 81, 81))
        self.la_cameraicon.setStyleSheet("border-image: url(picture/cameraicon.jpg);")
        self.la_cameraicon.setText("")
        self.la_cameraicon.setObjectName("la_cameraicon")
        self.la_robotc = QtWidgets.QLabel(self.page2)
        self.la_robotc.setGeometry(QtCore.QRect(340, 310, 211, 211))
        self.la_robotc.setStyleSheet("border-image: url(picture/robot_c.jpg);")
        self.la_robotc.setText("")
        self.la_robotc.setObjectName("la_robotc")
        self.la_robotc.lower()

        # self.setCentralWidget(self.centralwidget)

    def Page3(self):
        self.page3 = QtWidgets.QWidget(self.centralwidget)
        self.page3.setGeometry(QtCore.QRect(170, 90, 571, 741))
        # self.page3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.page3.setObjectName("page3")
        self.tableWidget = QTableWidget(self.page3)
        self.tableWidget.setGeometry(QtCore.QRect(30, 50, 531, 631))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.tableWidget.verticalHeader().setDefaultSectionSize(80)
        self.tableWidget.setColumnCount(2)

        self.la_page3 = QtWidgets.QLabel(self.page3)
        self.la_page3.setGeometry(QtCore.QRect(-10, -213, 611, 1151))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        self.la_page3.setFont(font)
        self.la_page3.setStyleSheet("border-image: url(picture/page3_picture.jpg);")
        self.la_page3.setText("")
        self.la_page3.setObjectName("la_page3")
        # self.la_page3.lower()
        self.outputfile = QtWidgets.QPushButton(self.page3)
        self.outputfile.setGeometry(QtCore.QRect(30, 680, 121, 37))
        self.outputfile.setObjectName("outputfile")
        self.outputfile.setStyleSheet("#outputfile{\n"
                                         "    background-color: rgb(255, 255, 255);\n"
                                         "    color: rgb(0, 0, 0);\n"
                                         "    border:3px solid rgb(182, 182, 182);\n"
                                         "    border-radius:8px;\n"
                                         "}\n"
                                         "#outputfile:hover{\n"
                                         "    background-color: rgb(249, 248, 222);\n"
                                         "    color: rgb(0, 0, 0);\n"
                                         "}\n"
                                         "#outputfile:pressed{\n"
                                         "    padding-top:5px;\n"
                                         "    padding-left:5px;\n"
                                         "}")
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 R")
        font.setPointSize(10)
        self.outputfile.setFont(font)

        item = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)

    def connect(self):
        """
        控件信号-槽的设置
        :param : QDialog类创建的对象
        :return: None
        """
        self.signal_write_msg.connect(self.write_msg)
        # self.comboBox_tcp.currentIndexChanged.connect(self.combobox_change)

    def write_msg(self, msg):
        # signal_write_msg信号会触发这个函数
        """
        功能函数，向接收区写入数据的方法
        信号-槽触发
        tip：PyQt程序的子线程中，直接向主线程的界面传输字符是不符合安全原则的
        :return: None
        """
        self.textBrowser_recv.insertPlainText(msg)
        # 滚动条移动到结尾
        self.textBrowser_recv.moveCursor(QtGui.QTextCursor.End)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "变电站巡检机器人系统"))
        self.label.setText(_translate("MainWindow", "串口号"))
        self.comboBox.setItemText(0, _translate("MainWindow", "COM1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "COM2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "COM3"))
        self.label_2.setText(_translate("MainWindow", "波特率"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "115200"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "57600"))
        self.label_ip.setText(_translate("MainWindow", "设备IP地址"))
        self.label_3.setText(_translate("MainWindow", "端口号"))
        self.label_4.setText(_translate("MainWindow", "海康相机实时画面"))
        self.picture_output1.setText(_translate("MainWindow", "camera not open"))
        self.label_6.setText(_translate("MainWindow", "仪表指针与表盘定位结果图"))
        self.picture_output2.setText(_translate("MainWindow", "wait reading"))
        self.label_8.setText(_translate("MainWindow", "仪表类别"))
        self.label_9.setText(_translate("MainWindow", "自动读数结果"))

#-----------------------------------------page1-------------------------------------------------------------#
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "仪表搜寻与自动读数控制"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "机体与相机云台运动控制"))
        item = self.listWidget.item(6)
        item.setText(_translate("MainWindow", "仪表识别结果对比显示"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.getipbutton.setText(_translate("MainWindow", "获取IP"))
        self.clearrev.setText(_translate("MainWindow", "清空"))
        self.sendbutton.setText(_translate("MainWindow", "发送"))
        self.pushButton_9.setText(_translate("MainWindow", "连接网络"))
        self.pushButton_10.setText(_translate("MainWindow", "断开网络"))
        self.Buton_cameraopen.setText(_translate("MainWindow", "打开摄像头"))
        self.Buton_cameraclose.setText(_translate("MainWindow", "关闭摄像头"))
        self.pushButton_13.setText(_translate("MainWindow", "仪表搜索"))
        self.pushButton_14.setText(_translate("MainWindow", "结束搜索"))
        self.save_picture.setText(_translate("MainWindow", "保存图片"))
        self.pushButton_16.setText(_translate("MainWindow", "导入数据"))
        self.label_35.setText(_translate("MainWindow", "巡检机器人返回数据"))
        self.label_36.setText(_translate("MainWindow", "电脑发送指令:"))


# -----------------------------------------page2-------------------------------------------------------------#
        self.label_37.setText(_translate("MainWindow", "云台转动角度"))
        self.label_38.setText(_translate("MainWindow", "机器人运动距离"))
        self.label_39.setText(_translate("MainWindow", "机器人移动速度"))
        self.label_40.setText(_translate("MainWindow", "机器人云台控制"))
        self.label_41.setText(_translate("MainWindow", "机器人机体控制"))
        self.label_42.setText(_translate("MainWindow", "相机焦距和倍率调节"))
        self.plus_2.setText(_translate("MainWindow", "+"))
        self.minus_2.setText(_translate("MainWindow", "-"))

# -----------------------------------------page3-------------------------------------------------------------#

        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "表类型"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "读数"))
        self.outputfile.setText(_translate("MainWindow", "保存数据"))